package com.visionsystems.waterreminder.presenter.ui.theme

import androidx.compose.ui.graphics.Color

val HydroPrimary = Color(0xFF0E7C86)
val HydroPrimaryDark = Color(0xFF0A5F66)
val HydroOnPrimary = Color(0xFFFFFFFF)
val HydroOnPrimaryMuted = Color(0xFFCDEDEC)
val HydroOnPrimarySoft = Color(0xFFE4F5F4)
val HydroPrimaryContainer = Color(0xFFCDEDEC)
val HydroPrimaryTint = Color(0xFFE3F4F3)
val HydroBackground = Color(0xFFF2FAF9)
val HydroSurface = Color(0xFFFFFFFF)
val HydroAccent = Color(0xFFFF7A59)
val HydroCoral = Color(0xFFEF6A45)
val HydroCoralTint = Color(0xFFFFE9E2)
val HydroCoralInk = Color(0xFFC24A26)
val HydroInk = Color(0xFF102A2C)
val HydroInkMuted = Color(0xFF5B7275)
val HydroOutline = Color(0xFFDCEBEA)
val HydroLine = Color(0xFFE6F1F0)
val HydroDivider = Color(0xFFEEF5F4)
val HydroTrack = Color(0xFFD6EBEA)
val HydroDash = Color(0xFF9CC7C4)
val HydroBarSoft = Color(0xFF9FD8D3)
val HydroSegment = Color(0xFFE3F0EF)
val HydroLocked = Color(0xFF7C9593)
val HydroDanger = Color(0xFFB53E1C)
val HydroSunTint = Color(0xFFFFF1DA)
val HydroSunInk = Color(0xFFA5610C)
val HydroMoonTint = Color(0xFFE5E9FB)
val HydroMoonInk = Color(0xFF3D4DB0)
val HydroWater = Color(0xFF5FC8C0)
val HydroWaterLight = Color(0xFF8FE3DC)
val HydroWaterBubble = Color(0xFFCFF4F1)
val HydroGlassBack = Color(0xFF0B6C75)
val HydroScrim = Color(0x80102A2C)
